name: Packer CI Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Initialize Packer
        run: packer init packer
      
      - name: Check Packer Formatting
        run: |
          packer fmt --check packer/packer.pkr.hcl

      - name: Validate Packer Template
        run: |
            echo "DB_USERNAME: ${{ secrets.DB_USERNAME }}"
            echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
            echo "DB_NAME: ${{ secrets.DB_NAME }}"
            echo "DB_PORT: ${{ secrets.DB_PORT }}"
            echo "PORT: ${{ secrets.PORT }}"
            packer validate \
            -var "db_username=${{ secrets.DB_USERNAME }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_port=${{ secrets.DB_PORT }}" \
            -var "port=${{ secrets.PORT }}" \
            -var-file=packer/variables.pkrvars.hcl \
            packer/packer.pkr.hcl

