name: Packer CI Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Initialize Packer
        run: packer init packer
      
      - name: Check Packer Formatting
        run: |
          packer fmt --check packer/packer.pkr.hcl

      - name: Validate Packer Template
        run: |
            packer validate \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_AMI }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "vpc_id=${{ secrets.AWS_VPC_ID }}" \
            -var "demo_acc_id=${{ secrets.AWS_DEMO_ACC_ID }}" \
            -var "demo_acc_key=${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}" \
            -var "demo_acc_sec_key=${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}" \
            packer/packer.pkr.hcl

