name: Packer Build CI Workflow

on:
  pull_request:
    types:
      - closed  
    branches:
      - test-packer

jobs:
  build-image:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

  
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      # Step 4: Start PostgreSQL Service
      - name: Start PostgreSQL Service
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

      # Step 5: Configure PostgreSQL
      - name: Configure PostgreSQL
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.DB_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USERNAME }};"

      # Step 6: Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until sudo -u postgres psql -c "\l"; do
            echo "Waiting for postgres to be ready...";
            sleep 5;
          done

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}

          # Test user credentials
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          
          # New user credentials
          NEW_USER_EMAIL: ${{ secrets.NEW_USER_EMAIL }}
          NEW_USER_PASSWORD: ${{ secrets.NEW_USER_PASSWORD }}
          
          # Duplicate user email
          DUPLICATE_USER_EMAIL: ${{ secrets.DUPLICATE_USER_EMAIL }}
          
          # User first and last names
          TEST_USER_FIRST_NAME: ${{ secrets.TEST_USER_FIRST_NAME }}
          TEST_USER_LAST_NAME: ${{ secrets.TEST_USER_LAST_NAME }}
          NEW_USER_FIRST_NAME: ${{ secrets.NEW_USER_FIRST_NAME }}

          # Updated user data for PUT tests
          UPDATED_USER_FIRST_NAME: ${{ secrets.UPDATED_USER_FIRST_NAME }}
          UPDATED_USER_LAST_NAME: ${{ secrets.UPDATED_USER_LAST_NAME }}
          UPDATED_USER_PASSWORD: ${{ secrets.UPDATED_USER_PASSWORD }}
          
        run: |
          npm test

      - name: Build Application Artifact
        run: |
          npm install 
          zip -r app.zip *
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: app.zip

      - name: Download App Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-artifact

      - name: Check if app.zip exists
        run: |
          if [ -f "app.zip" ]; then
            echo "app.zip found."
          else
            echo "app.zip not found."
            exit 1
          fi



      - name: Build Packer Image
        run: |
            
            packer init packer/packer.pkr.hcl
            packer build \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_AMI }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "vpc_id=${{ secrets.AWS_VPC_ID }}" \
            -var "demo_acc_id=${{ secrets.AWS_DEMO_ACC_ID }}" \
            packer/packer.pkr.hcl | tee packer-output.log
        
      - name: Extract AMI ID
        id: extract-ami
        run: |
          AMI_ID=$(grep -oP 'ami-\w+' packer-output.log | tail -1)
          echo "AMI ID: $AMI_ID"
          echo "LATEST_AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Configure AWS Credentials (demo Account)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      # Step 4: Create a new Launch Template version with the AMI ID from Step 3
      - name: Create new Launch Template version
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }} \
            --source-version 1 \
            --version-description "Updated with latest AMI" \
            --launch-template-data "{\"ImageId\":\"${LATEST_AMI_ID}\"}"

      - name: Get Latest Launch Template Version
        id: fetch-latest-version
        run: |
          LATEST_VERSION=$(aws ec2 describe-launch-template-versions \
            --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }} \
            --query "sort_by(LaunchTemplateVersions[?VersionDescription=='Updated with latest AMI'], &VersionNumber)[-1].VersionNumber" \
            --output text)
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "Latest Version: $LATEST_VERSION"
      - name: Set Default Launch Template Version
        run: |
          aws ec2 modify-launch-template \
            --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }} \
            --default-version $LATEST_VERSION


      - name: Update Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP_NAME }} \
            --launch-template "LaunchTemplateName=${{ secrets.LAUNCH_TEMPLATE_NAME }},Version=${LATEST_VERSION}"

      # Step 6: Trigger Instance Refresh
      - name: Trigger Instance Refresh
        id: instance-refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP_NAME }} \
            --preferences "{\"InstanceWarmup\":300,\"MinHealthyPercentage\":50}" \
            --query "InstanceRefreshId" --output text)
          echo "refresh_id=$REFRESH_ID" >> $GITHUB_ENV
          echo "Refresh ID: $REFRESH_ID"


      # Step 7: Wait for Instance Refresh to Complete
      - name: Wait for Instance Refresh
        run: |
           while true; do
            REFRESH_INFO=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP_NAME }} \
              --instance-refresh-ids $REFRESH_ID)
            
            STATUS=$(echo "$REFRESH_INFO" | jq -r '.InstanceRefreshes[0].Status')
            PERCENTAGE=$(echo "$REFRESH_INFO" | jq -r '.InstanceRefreshes[0].PercentageComplete')
            STATUS_REASON=$(echo "$REFRESH_INFO" | jq -r '.InstanceRefreshes[0].StatusReason // "No reason provided"')
            
            echo "Current status: $STATUS ($PERCENTAGE% complete)"
            echo "Status reason: $STATUS_REASON"
            if [ "$STATUS" == "Successful" ]; then
              echo "Instance refresh completed successfully."
              exit 0
            elif [ "$STATUS" == "Failed" ]; then
              echo "Instance refresh failed."
              exit 1
            fi
            sleep 30
           done


      





      